### ISSUE TITLE
个人建议把所有引入的第三方库统一放在一起

### ISSUE THREAD

**Issue by Xiphin** [sdfsky/tipask#6]
参考PR #5，我个人建议把所有引入的第三方库统一放在一起，都放在/public/static/libs目录下，例如：
引入 https://github.com/fengyuanchen/cropper 的 cropper
Cropper图片截剪库总共有两个文件，分为:
CSS: cropper.min.css
JS: cropper.min.js
在/public/static/libs目录下新建cropper目录，再把两个文件(cropper.min.css和cropper.min.js)放入cropper目录下，再进行分别引入
CSS引入
<link href="{{ asset('/static/libs/cropper/cropper.min.css')}}" rel="stylesheet" />
JS引入
<script src="{{ asset('/static/libs/cropper/cropper.min.js') }}"></script>

这样做的好处是可以避免
/public/static/js 目录下出现CSS文件
/public/static/css 目录下出现JS文件

**Comment by sdfsky** [comment]
public/static 目录下本身就是第三方组件库，例如bootstrap等第三方组件就直接放在这目录下了
public/js 是系统模块下的js目录
public/css是系统模块下的css文件

**Comment by Xiphin** [comment]
目前你的项目的bootstrap，你是放在public/static/css目录下的，但实际上bootstrap目录下还有css、font、js文件夹，连bootstrap的js也包括在public/static/css目录下。

**Comment by sdfsky** [comment]
抱歉看错了， 看成另外一个项目了 。目前分的太细了，static静态资源还分成了css样式类型和js组件类型。这个稍后统一一下，有些整体性前端组件不好归类，直接放到static目录下。

**Comment by Xiphin** [comment]
统一放在public/static/libs目录下，刚好libs跟images目录是并列的，如果直接全放在public/static目录下，多了看着也不清爽
