### ISSUE TITLE
解析设置root /home/wwwroot/default/tipask3/public/，输入域名127.0.0.1/install，提示404

### ISSUE THREAD

**Issue by 892768447** [sdfsky/tipask#9]
public下没有install文件夹或者install.php文件。如何安装？

**Comment by sdfsky** [comment]
用的是apache还是nginx.
public目录下有.htaccess  apache伪静态规则.
nginx需要配置一下伪静态规则
伪静态配置如下：http://wenda.tipask.com/article/134

ps: public目录下确实没有install目录，url是路由控制的，确认一下伪静态规则有没有问题。

**Comment by 892768447** [comment]
嗯嗯。作为已经在论坛里搜索找到其它类似教程了。建议在3.0版本安装教程那里给出配置伪静态的步骤，
